# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [15]:
# Import torch

import torch
# Create random tensor
x = torch.rand (7,7)
x


tensor([[0.3489, 0.4017, 0.0223, 0.1689, 0.2939, 0.5185, 0.6977],
        [0.8000, 0.1610, 0.2823, 0.6816, 0.9152, 0.3971, 0.8742],
        [0.4194, 0.5529, 0.9527, 0.0362, 0.1852, 0.3734, 0.3051],
        [0.9320, 0.1759, 0.2698, 0.1507, 0.0317, 0.2081, 0.9298],
        [0.7231, 0.7423, 0.5263, 0.2437, 0.5846, 0.0332, 0.1387],
        [0.2422, 0.8155, 0.7932, 0.2783, 0.4820, 0.8198, 0.9971],
        [0.6984, 0.5675, 0.8352, 0.2056, 0.5932, 0.1123, 0.1535]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [16]:
# Create another random tensor
y = torch.rand(7, 10)

# Perform matrix multiplication 
z = torch.matmul(x, y)
z


tensor([[1.3087, 1.3396, 1.5488, 0.8784, 1.8288, 1.1181, 0.8965, 1.0504, 0.8327,
         1.1988],
        [1.5062, 2.6887, 2.9371, 1.6681, 2.5017, 1.3153, 1.3967, 1.7305, 1.5282,
         1.9505],
        [1.2718, 0.9275, 2.0102, 1.5436, 1.4548, 1.7328, 1.2884, 1.2517, 0.8691,
         1.7059],
        [1.1805, 1.5487, 1.7625, 0.9670, 1.7667, 1.2423, 0.9326, 1.2455, 1.1005,
         1.4910],
        [1.2794, 1.4683, 2.0117, 1.5436, 1.6700, 1.6125, 1.5941, 1.3595, 0.9035,
         1.7226],
        [2.2534, 1.8904, 2.9714, 2.1058, 2.7920, 2.1449, 1.7559, 1.8957, 1.3248,
         2.2427],
        [1.2087, 1.4568, 2.2802, 1.6778, 1.5580, 1.6803, 1.5540, 1.3788, 0.9838,
         1.8711]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [17]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
x = torch.rand(7,7)
y = torch.rand(7,10)

# Matrix multiply tensors
z = torch.matmul(x,y)

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [20]:
# Set random seed on the GPU
torch.cuda.manual_seed(0)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [22]:
# Set random seed
torch.manual_seed(0)

# Check for access to GPU
if torch.cuda.is_available():
    device = 'cuda'
else:
    device = 'cpu'

# Create two random tensors on GPU
x = torch.rand(2,5).to(device)
torch.manual_seed(0)
y = torch.rand(5, 3).to(device)


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [23]:
# Perform matmul on tensor_A and tensor_B
z = torch.matmul(x, y)

### 8. Find the maximum and minimum values of the output of 7.

In [24]:
# Find max
print (z.max())
# Find min
print (z.min())

tensor(1.7071, device='cuda:0')
tensor(0.4814, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [25]:
# Find arg max
print(z.argmax())

# Find arg min
print (z.argmin())

tensor(4, device='cuda:0')
tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [27]:
# Set seed

torch.manual_seed(0)
# Create random tensor

x = torch.rand(1,1,1,10)
# Remove single dimensions
x = x.squeeze()

# Print out tensors and their shapes
x

tensor([0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901, 0.8964, 0.4556,
        0.6323])